backend/models/Employees.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "employees".
 *
 * @property int $id
 * @property string $employee
 * @property string $date
 * @property string $time_start
 * @property string $time_end
 * @property string $task_description
 */
class Employees extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'employees';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['employee', 'date', 'time_start', 'time_end', 'task_description'], 'required'],
            [['date', 'time_start', 'time_end'], 'safe'],
            [['task_description'], 'string'],
            [['employee'], 'string', 'max' => 150],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'employee' => 'Employee',
            'date' => 'Date',
            'time_start' => 'Time Start',
            'time_end' => 'Time End',
            'task_description' => 'Task Description',
        ];
    }

    public function beforeSave($insert)
    {
        if (!parent::beforeSave($insert)) {
            return false;
        }

        $this->date = strtotime($this->date);

        $timeS = explode(':', $this->time_start);
        $timeE = explode(':', $this->time_end);

        $this->time_start = mktime($timeS[0], $timeS[1], 0, date('m', $this->date), date('d', $this->date), date('Y', $this->date));
        $this->time_end = mktime($timeE[0], $timeE[1], 0, date('m', $this->date), date('d', $this->date), date('Y', $this->date));

        return true;
    }

    public function afterFind()
    {
        $this->time_start = Yii::$app->formatter->asTime($this->time_start);
        $this->time_end = Yii::$app->formatter->asTime($this->time_end);
        $this->date = date('d.m.Y', $this->date);

        return parent::afterFind();
    }
}

frontend/models/Employees.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "employees".
 *
 * @property int $id
 * @property string $employee
 * @property string $date
 * @property string $time_start
 * @property string $time_end
 * @property string $task_description
 */
class Employees extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'employees';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['employee', 'date', 'time_start', 'time_end', 'task_description'], 'required'],
            [['date', 'time_start', 'time_end'], 'safe'],
            [['task_description'], 'string'],
            [['employee'], 'string', 'max' => 150],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'employee' => 'Employee',
            'date' => 'Date',
            'time_start' => 'Time Start',
            'time_end' => 'Time End',
            'task_description' => 'Task Description',
        ];
    }

    public function beforeSave($insert)
    {
        if (!parent::beforeSave($insert)) {
            return false;
        }

        $date = explode('.', $this->date);
        $this->date = mktime(0,0,0, $date[1], $date[0], $date[2]);
        //$this->date = strtotime($this->date);

        $timeS = explode(':', $this->time_start);
        $timeE = explode(':', $this->time_end);

        $this->time_start = mktime($timeS[0], $timeS[1], 0, date('m', $this->date), date('d', $this->date), date('Y', $this->date));
        $this->time_end = mktime($timeE[0], $timeE[1], 0, date('m', $this->date), date('d', $this->date), date('Y', $this->date));

        return true;
    }

    public function afterFind()
    {
        $this->time_start = Yii::$app->formatter->asTime($this->time_start);
        $this->time_end = Yii::$app->formatter->asTime($this->time_end);
        $this->date = date('d.m.Y', $this->date);

        return parent::afterFind();
    }
}

backend/controllers/EmployeesController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Employees;
use backend\models\SearchEmployees;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EmployeesController implements the CRUD actions for Employees model.
 */
class EmployeesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'create', 'view', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                    'delete' => ['POST']
                ],
            ],
        ];
    }


    /**
     * Lists all Employees models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SearchEmployees();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Employees model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Employees model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Employees();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Employees model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Employees model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Employees model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Employees the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Employees::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }



/*
    public function actionIndex()
    {
        $client = new Client(['baseUrl' => 'http://path_to_host/rest/web/']);
        $response = $client->createRequest()
            ->setUrl('employee')
            ->addHeaders(['content-type' => 'application/json'])
            ->send();
        $data = Json::decode($response->content);
        $dataProvider = new ArrayDataProvider([
            'allModels' => $data,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }
*/
}

frontend/controllers/EmployeesController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Employees;
use frontend\models\SearchEmployees;
use yii\data\ArrayDataProvider;
use yii\helpers\Json;
use yii\httpclient\Client;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EmployeesController implements the CRUD actions for Employees model.
 */
class EmployeesController extends Controller
{
    /**
     * {@inheritdoc}
     */

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                ],
            ],
        ];
    }


    /**
     * Lists all Employees models.
     * @return mixed
     */
    public function actionIndex()
    {
        $client = new Client();
        $response = $client->createRequest()
            ->setMethod('GET')
            ->setUrl('http://berkleapi.ee/v1/employees')
            //->setData(['name' => 'John Doe', 'email' => 'johndoe@example.com'])
            ->addHeaders(['content-type' => 'application/json'])
            ->send();
        $data = Json::decode($response->content);
        $dataProvider = new ArrayDataProvider([
            'allModels' => $data,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);

        $searchModel = new SearchEmployees();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

        /*
        $searchModel = new SearchEmployees();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
        */
    }

    /**
     * Displays a single Employees model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Employees model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Employees();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Finds the Employees model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Employees the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Employees::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

frontend/views/employees/_form.php
<?php

use kartik\date\DatePicker;
use kartik\time\TimePicker;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Employees */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="employees-form">

    <div id="result"></div>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'employee')->textInput(['maxlength' => true]) ?>

    <?php

    echo $form->field($model, 'date')->widget(DatePicker::className(), [
        'name' => 'date',
        'value' => date('d.m.Y', strtotime($model->date)),
        'convertFormat' => true,
        'type' => DatePicker::TYPE_COMPONENT_APPEND,
        'options' => ['placeholder' => 'Select date ...'],
            'pluginOptions' => [
                'autoclose' => true,
                'format' => 'dd.MM.yyyy',
                'todayHighlight' => true,
            ],
            'pluginEvents' => [
                //"changeDate" => "function(e) { alert('date changed') }",
            ]
        ]);

    echo $form->field($model, 'time_start')->widget(TimePicker::classname(), [
        'name' => 'time_start',
        //'value' => '11:24 AM',
        'value' => Yii::$app->formatter->asTime($model->time_start),
        'pluginOptions' => [
            'showSeconds' => false,
            'minuteStep' => 15,
            'showMeridian' => false,
        ],
        'pluginEvents' => [
            "change" => "function(e) { 
            
               // console.log(e);
               checkTime(e);
 
            }",
        ]
    ]);

    echo $form->field($model, 'time_end')->widget(TimePicker::classname(), [
            'name' => 'time_end',
          //  'value' => '11:24 AM',
            'pluginOptions' => [
                'showSeconds' => false,
                'minuteStep' => 15,
                'showMeridian' => false,
            ]
        ]);
    ?>

    <?= $form->field($model, 'task_description')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success', 'id' => 'btnSubmit']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/employees/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Employees */

$this->title = 'Create Employees';
$this->params['breadcrumbs'][] = ['label' => 'Employees', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employees-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/employees/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\SearchEmployees */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Employees';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employees-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Employees', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'formatter' => [
            'class' => '\yii\i18n\Formatter',
            'dateFormat' => 'MM/dd/yyyy',
            'datetimeFormat' => 'HH:mm',
        ],

        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'employee',
            'date',
            'time_start:datetime',
            'time_end:datetime',
            'task_description:ntext',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}',
                'buttons' => [
                    'view' => function ($url, $model) {
                        $url = Url::to(['employees/view', 'id' => $model['id']]);
                        return Html::a('<span class="fa fa-eye">view</span>', $url, ['title' => 'view']);
                    },
                ],
            ],
        ],
    ]); ?>


</div>

frontend/views/employees/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Employees */

$this->title = $model->employee;
$this->params['breadcrumbs'][] = ['label' => 'Employees', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="employees-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'formatter' => [
            'class' => '\yii\i18n\Formatter',
            'dateFormat' => 'MM/dd/yyyy',
            'datetimeFormat' => 'HH:mm',
        ],
        'attributes' => [
            'id',
            'employee',
            'date',
            'time_start:datetime',
            'time_end:datetime',
            'task_description:ntext',
        ],
    ]) ?>

</div>